# Generated by Django 5.0.3 on 2024-04-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxnote', '0002_note_delete_messagevocal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_creation',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
